In [1]:
#import libraries for data Cleaning
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw_data.csv")

In [3]:
df.head(5)          #to get first 5 rows

,employee_id,first_name,last_name,email,gender,age,location,department,role,experience_years,tenure_years,salary_band,bonus,performance_score,training_hours,overtime_hours,projects_assigned,satisfaction_score,work_life_balance,attrition
0,1001,Tiffany,Hamilton,tiffanyhamilton692@gmail.com,Male,29,Mumbai,Operations,Senior Associate,2,0.55,Low,3286,1.66,46.0,12.92,10,65.66,3.02,0
1,1002,Brenda,Lewis,brendalewis540@gmail.com,Female,34,Hyderabad,Engineering,Associate,12,4.19,Low,1695,4.36,NaN,14.55,6,75.40,3.33,0
2,1003,Brittany,Williams,brittanywilliams206@gmail.com,Female,46,Bangalore,Marketing,Senior Associate,8,6.72,Low,4090,4.78,83.0,6.35,8,44.82,3.26,0
3,1004,Margaret,Maddox,margaretmaddox384@gmail.com,Female,55,Mumbai,Operations,Lead,7,3.61,Low,4136,1.54,88.0,9.01,2,55.83,4.92,1
4,1005,Kimberly,Miller,kimberlymiller794@gmail.com,Female,40,Pune,Human Resources,Associate,2,0.78,Medium,1198,2.06,55.0,15.60,5,62.90,1.26,0

In [4]:
df.tail(2)

,employee_id,first_name,last_name,email,gender,age,location,department,role,experience_years,tenure_years,salary_band,bonus,performance_score,training_hours,overtime_hours,projects_assigned,satisfaction_score,work_life_balance,attrition
34998,35999,Manuel,Daniels,manueldaniels131@gmail.com,Male,30,Chennai,Sales,Senior Associate,6,3.52,Low,6808,2.94,22.0,9.95,4,70.67,4.67,0
34999,36000,Connie,Woods,conniewoods295@gmail.com,Male,43,Chennai,Operations,Lead,6,9.56,Low,6471,3.05,100.0,10.98,4,64.85,4.95,0

In [5]:
df.shape

(35000, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         35000 non-null  int64
 1   first_name          35000 non-null  object
 2   last_name           35000 non-null  object
 3   email               35000 non-null  object
 4   gender              35000 non-null  object
 5   age                 35000 non-null  int64
 6   location            35000 non-null  object
 7   department          35000 non-null  object
 8   role                35000 non-null  object
 9   experience_years    35000 non-null  int64
 10  tenure_years        35000 non-null  float64
 11  salary_band         35000 non-null  object
 12  bonus               35000 non-null  int64
 13  performance_score   35000 non-null  float64
 14  training_hours      34300 non-null  float64
 15  overtime_hours      35000 non-null  float64
 16  projects_assigned   35000 non-null  int64
 17  satisfaction_score  34300 non-null  float64
 18  work_life_balance   35000 non-null  float64
 19  attrition           35000 non-null  int64
dtypes: float64(6), int64(6), object(8)
memory usage: 5.3+ MB

In [7]:
df.describe()

,employee_id,age,experience_years,tenure_years,bonus,performance_score,training_hours,overtime_hours,projects_assigned,satisfaction_score,work_life_balance,attrition
count,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,34300.000000,35000.000000,35000.000000,34300.000000,35000.000000,35000.000000
mean,18500.500000,38.442657,7.463514,4.982602,4502.683171,3.008233,55.047697,10.240439,5.522714,70.079659,3.006670,0.204229
std,10103.774047,9.833551,4.623143,2.889458,2015.665905,1.152096,26.294719,5.551234,2.865111,9.993360,1.154307,0.403143
min,1001.000000,22.000000,0.000000,0.000000,1000.000000,1.000000,10.000000,-9.550000,1.000000,26.540000,1.000000,0.000000
25%,9750.750000,30.000000,3.000000,2.480000,2765.000000,2.010000,32.000000,6.680000,3.000000,63.370000,2.010000,0.000000
50%,18500.500000,38.000000,7.000000,4.970000,4494.000000,3.010000,55.000000,10.040000,6.000000,70.050000,3.020000,0.000000
75%,27250.250000,47.000000,11.000000,7.500000,6255.000000,4.000000,78.000000,13.482500,8.000000,76.810000,4.000000,0.000000
max,36000.000000,55.000000,15.000000,10.000000,8000.000000,5.000000,100.000000,35.000000,10.000000,109.130000,5.000000,1.000000

In [8]:
df.isnull().sum()

employee_id             0
first_name              0
last_name               0
email                   0
gender                  0
age                     0
location                0
department              0
role                    0
experience_years        0
tenure_years            0
salary_band             0
bonus                   0
performance_score       0
training_hours        700
overtime_hours          0
projects_assigned       0
satisfaction_score    700
work_life_balance       0
attrition               0
dtype: int64

In [9]:
# Fill numeric columns using median
df["training_hours"].fillna(df["training_hours"].median(), inplace=True)

In [10]:
df["satisfaction_score"].fillna(df["satisfaction_score"].median(), inplace=True)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df["overtime_hours"] = np.where(df["overtime_hours"] > 25, 25, df["overtime_hours"])

In [13]:
df.isnull().sum()
df.describe()

,employee_id,age,experience_years,tenure_years,bonus,performance_score,training_hours,overtime_hours,projects_assigned,satisfaction_score,work_life_balance,attrition
count,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000
mean,18500.500000,38.442657,7.463514,4.982602,4502.683171,3.008233,55.046743,10.138873,5.522714,70.079066,3.006670,0.204229
std,10103.774047,9.833551,4.623143,2.889458,2015.665905,1.152096,26.030437,5.177361,2.865111,9.892920,1.154307,0.403143
min,1001.000000,22.000000,0.000000,0.000000,1000.000000,1.000000,10.000000,-9.550000,1.000000,26.540000,1.000000,0.000000
25%,9750.750000,30.000000,3.000000,2.480000,2765.000000,2.010000,33.000000,6.680000,3.000000,63.560000,2.010000,0.000000
50%,18500.500000,38.000000,7.000000,4.970000,4494.000000,3.010000,55.000000,10.040000,6.000000,70.050000,3.020000,0.000000
75%,27250.250000,47.000000,11.000000,7.500000,6255.000000,4.000000,77.000000,13.482500,8.000000,76.650000,4.000000,0.000000
max,36000.000000,55.000000,15.000000,10.000000,8000.000000,5.000000,100.000000,25.000000,10.000000,109.130000,5.000000,1.000000

In [14]:
df.to_csv("../data/cleaned_data.csv", index=False)

In [15]:
# Check attrition rate
attrition_rate = df["attrition"].mean()*100
print(f"Overall Attrition Rate: {attrition_rate:.2f}%")

Overall Attrition Rate: 20.42%

In [16]:
# Average satisfaction per department
avg_satisfaction = df.groupby("department")["satisfaction_score"].mean()
print(avg_satisfaction)

department
Engineering        70.157611
Finance            70.112921
Human Resources    70.006498
Marketing          70.193997
Operations         70.004414
Sales              70.000784
Name: satisfaction_score, dtype: float64